### ISSUE TITLE
Better installation documentation 

### ISSUE THREAD

**Issue by benbalter** [GSA/pdf-filler#2]
E.g., how to run bundler

**Comment by ajb** [comment]
"Bamboo build" instructions are also confusing. Are you referring to the Bamboo stack on Heroku? It's deprecated: https://devcenter.heroku.com/articles/bamboo

**Comment by benbalter** [comment]
Yes, Bamboo stack, which is deprecated. The older stack (which you can still spin up apparently) comes with PDFtk pre-installed. The newer stacks don't have it, and would have to install manually somehow.
