### ISSUE TITLE
`KEY_REGEX` causes error on some versions of ruby

### ISSUE THREAD

**Issue by benbalter** [GSA/pdf-filler#3]
https://github.com/GSA-OCSIT/pdf-filler/blob/master/lib/pdf_filler.rb#L11

required for non-fillable PDF filling.

**Comment by kvuppala** [comment]
For the above non-fillable PDF filling, what is the Ruby version required?

We are using the below Rudy version and gems, but receiving the above error.

Here is the ruby version information:
ruby 1.8.7 (2012-06-29 patchlevel 370) [x86_64-linux]

Here is a list of the current Ruby Gems installed.

Ascii85 (1.0.2)
bundle (0.0.1)
bundler (1.2.2)
daemon_controller (1.1.0)
daemons (1.1.9, 1.1.0)
diff-lcs (1.1.3)
eventmachine (1.0.0, 0.12.10)
fastthread (1.0.7)
hashery (2.1.0, 2.0.1)
json (1.7.5, 1.5.1)
kramdown (0.14.0)
liquid (2.4.1, 2.2.2)
markdown (1.0.0)
multi_json (1.3.7, 1.3.6)
nokogiri (1.5.5, 1.4.4)
passenger (3.0.18)
pdf-forms (0.4.5, 0.4.4)
pdf-reader (1.2.0)
prawn (0.12.0)
props (1.0.0)
rack (1.4.1, 1.1.0)
rack-protection (1.2.0)
rack-test (0.6.2, 0.4.0)
rake (10.0.2, 0.9.2.2, 0.8.7)
rspec (2.11.0)
rspec-core (2.12.0, 2.11.1)
rspec-expectations (2.11.3)
rspec-mocks (2.11.3)
ruby-rc4 (0.1.5)
simplecov (0.6.4)
simplecov-html (0.5.3)
sinatra (1.3.3, 1.0)
stomp (1.2.7, 1.2.2)
textutils (0.2.0)
thin (1.5.0, 1.2.8)
tilt (1.3.3)
ttfunk (1.0.3)
webrat (0.7.3)

**Comment by benbalter** [comment]
I would recommend upgrading to the latest version of ruby (1.9.3). After a bit of research, it looks like Ruby changed its regular expression engine in 1.9, which may be causing the trouble. Do you have any information on the error message you receive?

Tested and working with `ruby 1.9.3p286 (2012-10-12 revision 37165) [x86_64-darwin12.2.0]`.

**Comment by jgrevich** [comment]
I think we can close this issue considering that Ruby 1.8.7 lost support after June 2013.  Please let us know if this exists in Ruby 1.9.3 or greater.
